### ISSUE TITLE
isScrollEnd()をまとめる

### ISSUE THREAD

**Issue by taguchi-k** [stv-ekushida/STV-Extensions#4]
@stv-ekushida 
`isScrollEnd()`を`UIScrollView`にまとめられそうです。

* 修正内容
    * `isScrollEnd()`を`UIScrollView`の`extension`にする
    * NITS: `CGRect`のプロパティに直接アクセス `self.bounds.size.height` -> `self.bounds.height`
* 効果
    * サブクラスの`UICollectionView`からも`UITableView`からも利用できる
    * `UIScrollView`からも`isScrollEnd()`が使えるようになる
    * 定義場所がひとつでOK

```Swift
import UIKit

extension UIScrollView {

    /// 最下セルまでスクロールしたか？
    func isScrollEnd() -> Bool {
        return self.contentOffset.y >= self.contentSize.height - self.bounds.height
    }
}

// MARK: - demo

let collectionView = UICollectionView(frame: .zero)

if collectionView.isScrollEnd() {
    print("scrollEnd")
}

let tableView = UITableView(frame: .zero)

if tableView.isScrollEnd() {
    print("scrollEnd")
}
```

**Comment by stv-ekushida** [comment]
本件、対応しました。
